name: Run scheduler script

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  schedule:
    # Adjust for UTC based on Zurich time (CET/CEST)
    - cron: '0 7 * * *'  # Run daily at 08:00 AM Zurich time (07:00 AM UTC during standard time)
    - cron: '0 16 * * *'  # Run daily at 05:00 PM Zurich time (04:00 PM UTC during standard time)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduler script
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python scheduler.py

  cleanup:
    runs-on: ubuntu-latest
    needs: run-script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Cleanup old workflow runs
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the new secret name
        run: |
          python cleanup_old_runs.py
