name: Run scheduler script

on:
  push:
    branches:
      - TELEGRAM_BOT_OPTIMIZATIONS  # Trigger on push to this branch
  schedule:
    - cron: '*/8 * * * *'  # Run every 8 minutes
  workflow_dispatch:
    branches:
      - TELEGRAM_BOT_OPTIMIZATIONS  # Allow manual triggering on this branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/TELEGRAM_BOT_OPTIMIZATIONS'  # Ensure job runs only on this branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify Python version 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduler script
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python scheduler.py

  cleanup:
    runs-on: ubuntu-latest
    needs: run-script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Cleanup old workflow runs
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
        run: |
          python cleanup_old_runs.py
